# Generated by Django 4.2.16 on 2024-11-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_formation_quiz_chapitre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapitre',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='chapitre',
            old_name='contenu',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='chapitre',
            name='titre',
        ),
        migrations.AddField(
            model_name='chapitre',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chapitre',
            name='title',
            field=models.CharField(default=244, max_length=200),
            preserve_default=False,
        ),
    ]
