# Generated by Django 4.2.16 on 2024-11-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_remove_quiz_questions_remove_quiz_titre_quiz_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='titre de quiz', max_length=200),
        ),
    ]
