# Generated by Django 4.2.16 on 2024-11-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_remove_profile_phone_number_profile_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_inscrit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
