# Generated by Django 4.2.16 on 2024-11-06 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0009_users_inscrit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users_inscrit',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='date_naissance',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phonenumber',
            new_name='telephone',
        ),
    ]
