# Generated by Django 4.2.16 on 2024-11-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0014_devoir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devoir',
            name='fichier',
            field=models.FileField(upload_to='devoirs/'),
        ),
    ]
