# Generated by Django 4.2.16 on 2024-11-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0015_alter_devoir_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapitre',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='learn/media/'),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='devoirs/'),
        ),
    ]
