# Generated by Django 4.2.16 on 2024-11-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0016_alter_chapitre_fichier_alter_devoir_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='devoir',
            name='note',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='devoir',
            name='titre',
            field=models.CharField(max_length=100),
        ),
    ]
