# Generated by Django 4.2.16 on 2024-11-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0017_devoir_note_alter_devoir_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devoir',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
