# Generated by Django 4.2.16 on 2024-11-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0018_alter_devoir_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
