# Generated by Django 4.2.16 on 2024-11-08 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0020_remove_profile_bio_remove_profile_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediteur', models.CharField(choices=[('ETUDIANT', 'Étudiant'), ('ENSEIGNANT', 'Enseignant'), ('ADMIN', 'Administrateur')], max_length=50)),
                ('sujet', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recu', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
