# Generated by Django 4.2.16 on 2024-11-08 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0021_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['date_envoi']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='expediteur',
        ),
        migrations.RemoveField(
            model_name='message',
            name='lu',
        ),
        migrations.AddField(
            model_name='message',
            name='expéditeur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyés', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='destinataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_reçus', to=settings.AUTH_USER_MODEL),
        ),
    ]
