# Generated by Django 4.2.16 on 2024-11-09 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0024_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='destinataire',
        ),
        migrations.RemoveField(
            model_name='message',
            name='expediteur',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
