# Generated by Django 4.2.16 on 2024-11-09 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0026_message_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sent_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='message',
            name='read_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
    ]
