# Generated by Django 4.2.16 on 2024-11-09 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0027_alter_message_options_rename_body_message_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='to_user',
        ),
    ]
